version: '3.8'

services:
    
    frontend:
    
        build: 
            dockerfile: ./frontend/Dockerfile
            context: .
        ports:
          - 4444:4444
          
        volumes:
          - ./:/app
          
        networks:
            - app-network
                      
        command: streamlit run ./frontend/index.py --server.port 4444    
        
    inventory: 
    
        restart: always
        
        build:
            dockerfile: ./inventory/Dockerfile
            context: .
        
        ports:
            - 8000:8000
            
        expose:
            - '8000'     
            
        volumes:
            - .:/app

            
        # depends_on:
        #     - redis
            
        networks:
            - app-network
            
        command: uvicorn inventory.main:app --host 0.0.0.0 --port 8000 --debug --reload
    
        
    inventory-consumer:
        restart: always
        
        build:
            dockerfile: ./inventory/Dockerfile
            context: .
        
        volumes:
          - ./:/app
        
        networks:
            - app-network
          
        command: python ./inventory/consumer.py
        
    payment:
    
        restart: always
        
        build: 
            dockerfile: ./payment/Dockerfile
            context: .
        
        ports:
            - 8001:8001
            
        expose:
            - '8001'
            
        volumes:
            - .:/app
            
        # depends_on:
        #     - redis
            
        networks:
            - app-network
        
        command: uvicorn payment.main:app --host 0.0.0.0 --port 8001 --debug --reload
        
    payment-consumer:
        
        restart: always
        
        build:
            dockerfile: ./payment/Dockerfile
            context: .
        
        volumes:
          - ./:/app
          
        networks:
            - app-network
            
        command: python ./payment/consumer.py
        
networks:

    app-network:
        
        driver: bridge